import type { LucideIcon } from "lucide-react";
import {
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  BarChart3,
  Bot,
  Boxes,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  CircleCheck,
  CircleDot,
  Clock,
  Code2,
  Copy,
  Cpu,
  Database,
  ExternalLink,
  Eye,
  FileText,
  Filter,
  Gauge,
  GitBranch,
  History,
  Layers,
  LayoutGrid,
  Lock,
  MessageSquare,
  Network,
  Package,
  Pencil,
  Play,
  Plus,
  Radio,
  RefreshCw,
  RotateCcw,
  Scale,
  Search,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Target,
  ThumbsUp,
  Ticket,
  TrendingUp,
  Users,
  Workflow,
  X,
  Zap,
} from "lucide-react";
import type { SVGProps } from "react";

// A single icon surface for the whole app, backed by lucide-react. Call sites
// keep using <Icon name="…" />; sizing is driven by CSS (see globals.css
// `svg { height: auto }`), so lucide's default 24×24 scales uniformly.

const ICONS = {
  alert: AlertTriangle,
  analytics: BarChart3,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  bot: Bot,
  boxes: Boxes,
  check: CircleCheck,
  checkFilled: CheckCircle2,
  chevron: ChevronRight,
  chevronDown: ChevronDown,
  circleDot: CircleDot,
  clock: Clock,
  code: Code2,
  close: X,
  copy: Copy,
  cpu: Cpu,
  database: Database,
  externalLink: ExternalLink,
  eye: Eye,
  fileText: FileText,
  filter: Filter,
  gauge: Gauge,
  gitBranch: GitBranch,
  history: History,
  layers: Layers,
  lock: Lock,
  message: MessageSquare,
  network: Network,
  overview: LayoutGrid,
  package: Package,
  pencil: Pencil,
  play: Play,
  plus: Plus,
  radio: Radio,
  refresh: RefreshCw,
  replay: RotateCcw,
  scale: Scale,
  search: Search,
  shield: ShieldCheck,
  sliders: SlidersHorizontal,
  sparkles: Sparkles,
  target: Target,
  thumbsUp: ThumbsUp,
  ticket: Ticket,
  trending: TrendingUp,
  users: Users,
  workflow: Workflow,
  zap: Zap,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

export function Icon({ name, ...props }: SVGProps<SVGSVGElement> & { name: IconName }) {
  const LucideGlyph = ICONS[name];
  return <LucideGlyph aria-hidden="true" {...props} />;
}
